[package]
name = "reflection"
version = "0.1.0"
edition = "2024"
authors = [
  "adz <x12@adz.garden>",
  "sandreae <contact@samandreae.com>",
  "Julian Sparber <julian@sparber.net>",
]

[dependencies]
reflection-doc = { path = "../reflection-doc" }
anyhow = "1"
ratatui = { version = "0.27", features = ["crossterm"] }
crossterm = "0.27"
tokio = { version = "1.48", features = ["rt-multi-thread", "macros", "time"] }
glib = "0.21"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
